### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by mdosch** [schmidtandreas/wofi-pass#10] opened 2024-01-17 20:38 UTC
Dear Andreas,

I tried to run the tests with bash_unit but some fail for me:

```
bash_unit tests/*
Running tests in tests/test_args
	Running test_args_autotype ... SUCCESS ✓ 
	Running test_args_copy ... SUCCESS ✓ 
	Running test_args_fileisuser ... SUCCESS ✓ 
	Running test_args_help ... SUCCESS ✓ 
	Running test_args_squash ... SUCCESS ✓ 
	Running test_args_type ... SUCCESS ✓ 
	Running test_args_unknown ... FAILURE ✗ 
args: parsed not defined parameter
 expected regex [.*unrecognized option.*] to match [wofi-pass: Unbekannte Option »--not-exist«]
test_args:70:test_args_unknown()
```
So it seems to fail if the locale is not english. But also with an english locale some tests fail:

```
LC_ALL=C bash_unit tests/*
Running tests in tests/test_args
	Running test_args_autotype ... SUCCESS \u2713 
	Running test_args_copy ... SUCCESS \u2713 
	Running test_args_fileisuser ... SUCCESS \u2713 
	Running test_args_help ... SUCCESS \u2713 
	Running test_args_squash ... SUCCESS \u2713 
	Running test_args_type ... SUCCESS \u2713 
	Running test_args_unknown ... SUCCESS \u2713 
Running tests in tests/test.conf
Running tests in tests/test_config
	Running test_config_get_custom_config_file ... SUCCESS \u2713 
	Running test_config_get_global_config_file ... FAILURE \u2717 
config get file: get global config file failed
 expected [/etc/wofi-pass.conf] but was [/home/martin/.config/wofi-pass/config]
test_config:67:test_config_get_global_config_file()
	Running test_config_get_user_config_file ... FAILURE \u2717 
config: test environment contains /home/martin/.config/wofi-pass/config
test_config:36:test_config_get_user_config_file()
	Running test_config_load_empty ... test_config: line 19: COPROC: command not found
FAILURE \u2717 
config load: mock get_config_file not executed
 expected regex [.*FAKE_PARAMS.*] to match []
test_config:21:test_config_load_empty()
	Running test_config_load_test_conf ... SUCCESS \u2713 
Running tests in tests/test_get_field
	Running test_get_field_mulitfields ... SUCCESS \u2713 
	Running test_get_field_password_only ... SUCCESS \u2713 
Running tests in tests/test_get_output_cmd
	Running test_get_output_cmd ... SUCCESS \u2713 
Running tests in tests/test_get_passname
	Running test_passname_change_pass_store_dir ... SUCCESS \u2713 
	Running test_passname_empty_input ... SUCCESS \u2713 
	Running test_passname_selection ... SUCCESS \u2713 
Running tests in tests/test_help
	Running test_exit_help_flag_not_set ... SUCCESS \u2713 
	Running test_exit_help_flag_set ... SUCCESS \u2713 
Running tests in tests/test_output_autotype
	Running test_output_autotype_customize_username ... SUCCESS \u2713 
	Running test_output_autotype_default ... SUCCESS \u2713 
	Running test_output_autotype_single_keyword ... SUCCESS \u2713 
Running tests in tests/test_output_field
	Running test_output_field_autotype ... SUCCESS \u2713 
	Running test_output_field_single_selection ... SUCCESS \u2713 
Running tests in tests/test_parse_fields
	Running test_parse_fields_autotype ... SUCCESS \u2713 
	Running test_parse_fields_empty_password ... SUCCESS \u2713 
	Running test_parse_fields_ignore ... SUCCESS \u2713 
	Running test_parse_fields_only_password ... SUCCESS \u2713 
	Running test_parse_fields_otp ... SUCCESS \u2713 
	Running test_parse_fields_username_password ... SUCCESS \u2713 
Running tests in tests/test_pass_field
	Running test_pass_field ... SUCCESS \u2713 
Running tests in tests/test_pass_get
	Running test_pass_get_fileisuser ... SUCCESS \u2713 
	Running test_pass_get_other_fields ... SUCCESS \u2713 
	Running test_pass_get_otp ... SUCCESS \u2713 
	Running test_pass_get_password ... SUCCESS \u2713 
Running tests in tests/test_verify_flags
	Running test_flags_no_type_copy ... SUCCESS \u2713 
	Running test_flags_no_type_nor_copy ... SUCCESS \u2713 
	Running test_flags_type_and_copy ... SUCCESS \u2713 
	Running test_flags_type_no_copy ... SUCCESS \u2713 
Overall result: FAILURE \u2717 
```

I'm not sure what is causing this failures, but it seems to fail if it doesn't find the config files where it expects them.
I think those might be false-positives as wofi-pass is working well here with my config.

**Comment by schmidtandreas** [comment] 2024-01-19 12:31
Hello Martin,
thx for the hints.

For the issue regarding localisation: I have an idea how to fix that, I will try to do it.
For the issue regarding finding of config files: I need this test and it works for travis and arch-linux installation, due to fact that the package for arch-linux installs a default global config file in /etc. Could it be a approach for Debian too? Another approach here could be to us a docker for that, but it could mask some "issues" on the real local environment. So I would prefer to keep it that way.

**Comment by mdosch** [comment] 2024-01-19 16:13
Dear Andreas,

On 19.01.2024 04:32, Andreas Schmidt wrote:
>For the issue regarding finding of config files: I need this test and 
>it works for travis and arch-linux installation, due to fact that the 
>package for arch-linux installs a default global config file in /etc. 

thanks for the clarification. I will install the default config in 
debian as well.

**Comment by mdosch** [comment] 2024-01-19 16:29
Ok, running it in an english locale with `/etc/wofi-pass.conf` installed 
I get less errors, but there are still failing tests:

```
Running tests in tests/test.conf
Running tests in tests/test_config
	Running test_config_get_custom_config_file ... SUCCESS ✓ 
	Running test_config_get_global_config_file ... FAILURE ✗ 
config: test environment contains /etc/wofi-pass.conf
test_config:58:test_config_get_global_config_file()
	Running test_config_get_user_config_file ... FAILURE ✗ 
config: test environment contains /home/martin/.config/wofi-pass/config
test_config:36:test_config_get_user_config_file()
	Running test_config_load_empty ... test_config: line 19: COPROC: command not found
FAILURE ✗ 
config load: mock get_config_file not executed
  expected regex [.*FAKE_PARAMS.*] to match []
  ```

  Maybe I am missing a dependency here as there is a `command not found`.

**Comment by schmidtandreas** [comment] 2024-01-20 00:14
Regarding the COPROC: I oversee it in your logs. I could reproduce it and I guess I fixed it. (Checkout the last commit and feedback is welcome)
However the test regarding the config files, it is more complicate to fix. I have currently no idea how I can fix it.
At first: if you add the global config file for installation to the package, I guess it is the right decision. The benefit of it is that you will add a example config file. This file could be used for user config file as template.
Regaring false-positive test, just ignore it currently, also for user config (/home/user/.confi/wofi-pass/config)

**Comment by mdosch** [comment] 2024-01-20 07:57
Thanks, that fixed the failures except the config failures:

```
Running tests in tests/test_config
	Running test_config_get_custom_config_file ... SUCCESS ✓ 
	Running test_config_get_global_config_file ... FAILURE ✗ 
config: test environment contains /etc/wofi-pass.conf
test_config:58:test_config_get_global_config_file()
	Running test_config_get_user_config_file ... FAILURE ✗ 
config: test environment contains /home/martin/.config/wofi-pass/config
test_config:36:test_config_get_user_config_file()
```

Right now I can't add the tests to the debian package anyway, as 
bash_unit was not yet accepted, so once it is there I will figure out 
whether I'll disable the config tests for now

**Comment by AkechiShiro** [comment] 2024-02-04 23:08
Hi @schmidtandreas,

I've seen that some specific password are missing the first char when copied or maybe some are also missing some special symbols, maybe there is an issue with `wtype`, I need to further investigate, the issue to narrow down the ones where there are issues, maybe it could be something with my setup that is wrong.

I just want to know if the test could catch those cases ? or should they be improved ?

**Comment by mdosch** [comment] 2024-02-05 23:42
I only had this issue when I had to use chromium on sites not working with firefox. Chromium sometimes ate the first character. Iirc I don't have this issue anymore since putting a delay before the password: https://github.com/schmidtandreas/wofi-pass/blob/main/man/wofi-pass.1.ronn#autotype-format

Am 4. Februar 2024 23:08:22 UTC schrieb Samy Lahfa ***@***.***>:
>Hi @schmidtandreas,
>
>I've seen that some specific password are missing the first char when copied or maybe some are also missing some special symbols, maybe there is an issue with `wtype`, I need to further investigate, the issue to narrow down the ones where there are issues, maybe it could be something with my setup that is wrong.
>
>I just want to know if the test could catch those cases ? or should they be improved ?
>

**Comment by schmidtandreas** [comment] 2024-02-18 10:18
Hi @AkechiShiro 
the issue is on `wtype` side, I guess, see [this issue](https://github.com/atx/wtype/issues/46).
That's why I'm not going to extend any test to try to cover this issue until it is fixed on `wtype`.
One of the workarounds is mentioned by @mdosch already.

**Comment by schmidtandreas** [comment] 2024-02-18 13:13
Hi @mdosch,
I added some "ugly" skipping of the tests, that are dependent to environment. Unfortunately bash_utils has no mechanism for skipping the tests, so I reuse mechanism for "todo" or "pending" tests to skip the affected tests (if conditions are not fulfilled). I created [the issue](https://github.com/pgrange/bash_unit/issues/101) on bash_utils to handle this part more transparent.

**Comment by mdosch** [comment] 2024-02-19 19:07
Hi Andreas,

thank you very much. Looks good on my system. Now I only need to wait 
and hope debian accepts bash_unit, so I'll be able to also use it for 
autopkgtests for wofi-pass. :)

Best regards,
Martin

**Comment by schmidtandreas** [comment] 2024-02-22 09:24
The [issue](https://github.com/pgrange/bash_unit/issues/101) in bash_unit is closed and I adjusted the tests. Now both critical tests are skipped if files already exists to avoid conflicts while testing with user environment.
@mdosch Martin, thank you for the feedback!!! And I hope the bash_utils will be accepted by debian soon! Good luck!

**Closed as completed by schmidtandreas** 2024-02-22 09:24 UTC
Labels: bug, testing
