### ISSUE TITLE
PASSWORD_STORE_DIR not set for pass command

### ISSUE THREAD

**Issue by dechandler** [schmidtandreas/wofi-pass#13] opened 2024-02-22 11:44 UTC
Using an alternate PASSWORD_STORE_DIR defined in the wofi-pass config, the tree is loaded correctly, but it's not passed on to the call to pass.

Here's some scrubbed output to demonstrate what I'm seeing
```
~ $ [[ -z $PASSWORD_STORE_DIR ]]; echo $?
0

~ $ grep PASSWORD_STORE_DIR ~/var/pass/wofi-pers.conf
PASSWORD_STORE_DIR="${HOME}/var/pass/pers"

~ $ stat ~/.password-store
stat: cannot statx '/home/david/.password-store': No such file or directory

~ $ ls ~/var/pass/pers/github
pass.gpg  user.gpg

~ $ WOFI_PASS_CONFIG="$HOME/var/pass/wofi-pers.conf" ~/src/wofi-pass/wofi-pass -sc
Error: github/user is not in the password store.
Error: github/user is not in the password store.

~ $ WOFI_PASS_CONFIG="$HOME/var/pass/wofi-pers.conf" bash -x ~/src/wofi-pass/wofi-pass -sc
+ VERSION=23.1.5
+ set -eu
+ FLAG_AUTOTYPE=0
+ FLAG_COPY=0
+ FLAG_FILEISUSER=0
+ FLAG_ONLYPASSWORD=0
+ FLAG_SQUASH=0
+ FLAG_TYPE=0
+ FLAG_HELP=0
+ CMD_COPY=wl-copy
+ CMD_TYPE='wtype -'
+ PASS_FIELD_USERNAME=username
+ WOFI_PASS_AUTOTYPE=':username :tab :password'
+ WOFI_PASS_DELAY=2
+ WOFI_PASS_AUTO_ENTER=false
+ [[ -z '' ]]
+ main -sc
+ local passname
+ local field
+ load_config_file
++ get_config_file
++ local config_base_dir=/home/david/.config
++ readonly config_base_dir
++ config_files=("${WOFI_PASS_CONFIG:-""}" "${config_base_dir}/wofi-pass/config" "/etc/wofi-pass.conf")
++ for config in "${config_files[@]}"
++ [[ -n /home/david/var/pass/wofi-pers.conf ]]
++ [[ -f /home/david/var/pass/wofi-pers.conf ]]
++ printf %s /home/david/var/pass/wofi-pers.conf
++ return
+ config_file=/home/david/var/pass/wofi-pers.conf
+ [[ -n /home/david/var/pass/wofi-pers.conf ]]
+ source /home/david/var/pass/wofi-pers.conf
++ PASSWORD_STORE_DIR=/home/david/var/pass/pers
+ parse_arguments -sc
++ getopt --options ac::fhst:: --longoptions autotype,copy::,fileisuser,help,squash,type:: -n wofi-pass -- -sc
+ OPTS=' -s -c '\'''\'' --'
+ eval set -- ' -s -c '\'''\'' --'
++ set -- -s -c '' --
+ true
+ case "${1}" in
+ FLAG_SQUASH=1
+ shift
+ true
+ case "${1}" in
+ FLAG_COPY=1
+ '[' -n '' ']'
+ shift 2
+ true
+ case "${1}" in
+ shift
+ break
+ exit_if_help_flag_set
+ '[' 0 -eq 1 ']'
+ verify_flags
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 0 ']'
+ '[' 1 -eq 0 ']'
++ get_passname_from_menu
++ local -r pass_dir=/home/david/var/pass/pers
++ local password_files
+++ find /home/david/var/pass/pers -name '*.gpg'
+++ sed 's|^/home/david/var/pass/pers\/\(.*\)\.gpg$|\1|'
+++ sort
++ password_files='github/pass
github/user'
++ printf %s github/user
+ passname=github/user
+ '[' -n github/user ']'
++ get_field_from_menu github/user
++ local field
++ local field_count
++ local -r passname=github/user
++ mapfile -t field_list
+++ parse_fields github/user
+++ local field_list
+++ local has_username=0
+++ local -r passname=github/user
+++ mapfile -t entries
++++ _pass show github/user
++++ pass show github/user
++++ tail -n +2
Error: github/user is not in the password store.
+++ local line=
+++ fields=()
+++ local fields
+++ field_list+=("password")
+++ '[' 0 -eq 1 ']'
+++ '[' 0 -eq 1 ']'
+++ printf '%s\n' password
++ field_count=1
++ readonly field_list
++ readonly field_count
++ '[' 1 -eq 1 ']'
++ '[' 1 -le 1 ']'
++ printf password
++ FLAG_ONLYPASSWORD=1
+ field=password
+ output_field github/user password
+ local cmd_output
+ local -r passname=github/user
+ local -r field=password
++ get_output_cmd
++ '[' 0 -eq 1 ']'
++ printf %s wl-copy
+ cmd_output=wl-copy
+ '[' 0 -eq 1 ']'
+ '[' password = autotype ']'
+ pass_get github/user password
+ local -r passname=github/user
+ local -r field=password
+ wl-copy
+ '[' password = password ']'
+ _pass show github/user
+ pass show github/user
+ IFS=
+ read -r pass
Error: github/user is not in the password store.
```

**Comment by schmidtandreas** [comment] 2024-02-22 16:14
Hi @dechandler,
so ok I guess I can reproduce it. I guess also that the issue is, that due to using subshells the variables are not provided to the subshell right and `pass` did not "see" the `PASSWORD_STORE_DIR`. So a hot fix for you just add this to your wofi-config file:
```bash
function _pass() {
  PASSWORD_STORE_DIR="${PASSWORD_STORE_DIR}" pass "${@}"
}
```

**Comment by schmidtandreas** [comment] 2024-02-22 16:15
I will thing about it how to fix this issue.

**Comment by schmidtandreas** [comment] 2024-02-22 17:35
I did not find any other solutions for now. So I guess I will fix it in same way as the hot fix, that I provided to you.

**Comment by dechandler** [comment] 2024-02-23 00:05
Sounds good, thanks for taking a look and putting in a fix!

**Comment by schmidtandreas** [comment] 2024-02-23 13:19
Ok, then I close this issue.
The fix is [this](https://github.com/schmidtandreas/wofi-pass/commit/3e323f16e66cd4ee659e00d6c399a43aabc0ad2b) commit.

**Closed as completed by schmidtandreas** 2024-02-23 13:19 UTC
Labels: bug
